---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

body:
  - type: input
    attributes:
      label: Python version
    validations:
      required: true
  - type: input
    attributes:
      label: OS
    validations:
      required: true
